### ISSUE TITLE
Commit message not displaying properly

### ISSUE THREAD

**Issue by TarekVisch** [lostintangent/gitdoc#45]
Commit message being displayed as: `ddd, Aug 8/10/2022, YYYY, 7:15 A +0` 
![image](https://user-images.githubusercontent.com/53354285/184002379-5a6b351f-b9cf-427b-9565-f0f211fd46e4.png)

**Comment by rongxin-liu** [comment]
The issue is not with the extension, but the `gitdoc.commitMessageFormat` config specified in your `.devcontainer.json` file is no longer working properly, because the extension is now using `Luxon` instead of `Moment`. You should be using `ccc, LLL d, kkkk, h:mm a ZZ` instead of `ddd, MMM D, YYYY, h:mm A Z` per https://github.com/moment/luxon/blob/master/docs/formatting.md#table-of-tokens.

**Comment by TarekVisch** [comment]
issue fixed. Than you
